config/routes.rb
Collective::Application.routes.draw do
   
  root :to => 'static_pages#home'

  get "static_pages/contact"
  get "static_pages/index"
  get '/comunidad', to: 'static_pages#comunidad'
  get '/work', to: 'static_pages#work'
  get '/colectivo', to: 'static_pages#colectivo'
  get '/esencia', to: 'static_pages#esencia'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def contact
  end

  def home
  end

  def comunidad
  end

  def work
  end

  def colectivo
  end

  def esencia
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Collective</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/static_pages/_colectivo.html.erb
<div style="background-image: url(/assets/micro_carbon.png); overflow:hidden; margin-left:0%" class="row">
	<div style="overflow:hidden" id="letter-container" class="letter-container">
		<h2>
			<a href="#">ColumpiARTE lo hacemos muchos...</a>
		</h2>
	</div>
	<div id="container"> 
        <div style="margin-left:19%" id="txtlzr">
        	<p>Mucho Amor, Mucho Arte, Mucha Expresión, Mucha Organización, Mucha Música, 
        		Mucha Cultura, Mucho Diseño</p> <p>Muchos Corazones, Muchos Escenarios, 
        		Mucha Gente, Muchas Risas, Muchos Amigos</p><p> Muchos Sueños, Muchas Esperanzas, Muchas Alegrías, Muchas Ideas, Muchos Bailes, Mucho Compañerismo, Mucho México</p>
        </div> 
    </div> 
	
</div>

<div style="margin-left:0%" class="row">
	<div class="container">
		<div class="project_thumb">
			<div class="item">
				<div class="cardimgcrop">
					<img src="/assets/recuadro_1.png" border="0" rel="testprt_1341343299.png" style="opacity: 1;">
				</div>
			</div>
		</div>
		<div class="project_thumb">
			<div class="item">
				<div class="cardimgcrop">
					<img src="/assets/recuadro_2.png" border="0" rel="testprt_1341343316.gif" style="opacity: 1;">
				</div>
			</div>
		</div>
		<div class="project_thumb">
			<div class="item">
				<div class="cardimgcrop">
					<img src="/assets/recuadro_3.png" border="0" rel="testprt_1341343338.gif" style="opacity: 1;">
				</div>
			</div>
		</div>
		<div class="project_thumb">
			<div class="item">
				<div class="cardimgcrop">
					<img src="/assets/recuadro_4.png"border="0" rel="testprt_1341343354.gif" style="opacity: 1;">
				</div>
			</div>
		</div>
		<div class="project_thumb">
			<div class="item">
				<div class="cardimgcrop">
					<img src="/assets/recuadro_5.png"border="0" rel="testprt_1341343354.gif" style="opacity: 1;">
				</div>
			</div>
		</div>
	</div>
</div>
<div style="margin-left:0%" class="row">
	<div class="container">

		<div class="project_thumb">
			<div class="item">
				<div class="cardimgcrop">
					<img src="http://payload105.cargocollective.com/1/2/65848/4409757/prt_256x175_1352849177.png" border="0" rel="testprt_1352849177.png" style="opacity: 1;">
				</div>
			</div>
		</div>
		<div class="project_thumb">
			<div class="item">
				<div class="cardimgcrop">
					<img src="http://payload105.cargocollective.com/1/2/65848/4409757/prt_256x175_1352849177.png" border="0" rel="testprt_1352849177.png" style="opacity: 1;">
				</div>
			</div>
		</div>
		<div class="project_thumb">
			<div class="item">
				<div class="cardimgcrop">
					<img src="http://payload105.cargocollective.com/1/2/65848/4409757/prt_256x175_1352849177.png" border="0" rel="testprt_1352849177.png" style="opacity: 1;">
				</div>
			</div>
		</div>
		<div class="project_thumb">
			<div class="item">
				<div class="cardimgcrop">
					<img src="http://payload105.cargocollective.com/1/2/65848/4409757/prt_256x175_1352849177.png" border="0" rel="testprt_1352849177.png" style="opacity: 1;">
				</div>
			</div>
		</div>
	</div>
</div>
<div style="margin-left:0%" class="row">
	<div class="container">
		<div class="project_thumb">
			<div class="item">
				<div class="cardimgcrop">
					<img src="http://payload105.cargocollective.com/1/2/65848/4409757/prt_256x175_1352849177.png" border="0" rel="testprt_1352849177.png" style="opacity: 1;">
				</div>
			</div>
		</div>
		<div class="project_thumb">
			<div class="item">
				<div class="cardimgcrop">
					<img src="http://payload105.cargocollective.com/1/2/65848/4409757/prt_256x175_1352849177.png" border="0" rel="testprt_1352849177.png" style="opacity: 1;">
				</div>
			</div>
		</div>
		<div class="project_thumb">
			<div class="item">
				<div class="cardimgcrop">
					<img src="http://payload105.cargocollective.com/1/2/65848/4409757/prt_256x175_1352849177.png" border="0" rel="testprt_1352849177.png" style="opacity: 1;">
				</div>
			</div>
		</div>
		<div class="project_thumb">
			<div class="item">
				<div class="cardimgcrop">
					<img src="http://payload105.cargocollective.com/1/2/65848/4409757/prt_256x175_1352849177.png" border="0" rel="testprt_1352849177.png" style="opacity: 1;">
				</div>
			</div>
		</div>
	</div>
</div>
<div style="margin-left:0%" class="row">
	<div class="container">
		<div class="project_thumb">
			<div class="item">
				<div class="cardimgcrop">
					<img src="http://payload105.cargocollective.com/1/2/65848/4409757/prt_256x175_1352849177.png" border="0" rel="testprt_1352849177.png" style="opacity: 1;">
				</div>
			</div>
		</div>
		<div class="project_thumb">
			<div class="item">
				<div class="cardimgcrop">
					<img src="http://payload105.cargocollective.com/1/2/65848/4409757/prt_256x175_1352849177.png" border="0" rel="testprt_1352849177.png" style="opacity: 1;">
				</div>
			</div>
		</div>
		<div class="project_thumb">
			<div class="item">
				<div class="cardimgcrop">
					<img src="http://payload105.cargocollective.com/1/2/65848/4409757/prt_256x175_1352849177.png" border="0" rel="testprt_1352849177.png" style="opacity: 1;">
				</div>
			</div>
		</div>
		<div class="project_thumb">
			<div class="item">
				<div class="cardimgcrop">
					<img src="http://payload105.cargocollective.com/1/2/65848/4409757/prt_256x175_1352849177.png" border="0" rel="testprt_1352849177.png" style="opacity: 1;">
				</div>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
$(function(){
	$('.item').bind({
		mouseenter: function(){
			$(this).find('img').fadeTo('fast','0.7', function(){
				//
			});
			
		},
		mouseleave: function(){
			$(this).find('img').fadeTo('fast','1', function(){
				//
			});
			
		}
	});
});

$(function() {
	$("#letter-container h2 a").lettering();
});

$(function() {
          var txt = $('#txtlzr'); 
          txt.textualizer();
          txt.textualizer('start');
    })

</script>

app/views/static_pages/_comunidad.html.erb
<div class="worktitle">
  <h1 align="center" >El colectivo trabaja así</h1>
</div>
<div class="container-fluid">
  <div class="row">
    <div style="width:484px; height:291px; background-image: url('/assets/collective.png'); margin-top:5%" class="span2 offset3">
    </div>
  </div>
  <div class="row">
    <br>
    <div class="span8 offset2">
      <p class="textos">
        En <strong>ColumpiARTE</strong> trabajamos en conjunto de forma profesional, dedicada y llena de amor para impulsarte a alcanzar tus sueños. Amantes de nuestro trabajo, no sólo del resultado sino del proceso completo, la organización, la parte creativa y la producción. <br>
        El arte en movimiento. 
        <br>
        <strong>¡Queremos darte el empujón que necesitas para hacerte crecer!</strong>
        <br>
      </p>
    </div>
  </div>
</div>

app/views/static_pages/_esencia.html.erb
<div class="container">

</div>

app/views/static_pages/_work.html.erb
<div id="acc-menu2" style="position:relative; height: 100%; width: 100%;" class="aim">
  <a class="img_height" style="width: 510px; height: 100%; background-image: url(/assets/columna_1_planeacion.png; background-color: rgb(0, 0, 0); border-bottom-width: 0px; border-right-style: solid; border-right-width: 1px; border-right-color: rgb(0, 0, 0); overflow: hidden; background-repeat: no-repeat no-repeat;"><img class="alignnone size-medium wp-image-806" title="This street" src="/assets/columna_1_planeacion.png" alt="" style="display: none;"></a>
  <a class="img_height" style="width: 110px; height: 100%; background-image: url(/assets/columna_2_mercadotecnia.png); background-color: rgb(0, 0, 0); border-bottom-width: 0px; border-right-style: solid; border-right-width: 1px; border-right-color: rgb(0, 0, 0); overflow: hidden; background-repeat: no-repeat no-repeat;"><img class="alignnone size-medium wp-image-803" title="Bamboo" src="/assets/columna_2_mercadotecnia.png" alt="" width="300"  style="display: none;"></a>
  <a class="img_height" style="width: 110px; height: 100%; background-image: url(/assets/columna_3_redes_sociales.png); background-color: rgb(0, 0, 0); border-bottom-width: 0px; border-right-style: solid; border-right-width: 1px; border-right-color: rgb(0, 0, 0); overflow: hidden; background-repeat: no-repeat no-repeat;"><img class="alignnone size-medium wp-image-801" title="gift of light" src="/assets/columna_3_redes_sociales.png" alt="" width="241" style="display: none;"></a>
  <a class="img_height" style="width: 110px; height: 100%; background-image: url(/assets/columna_4_pomocionales.png); background-color: rgb(0, 0, 0); border-bottom-width: 0px; border-right-width: 0px; overflow: hidden; background-repeat: no-repeat no-repeat;"><img class="alignnone size-medium wp-image-800" title="Aerial" src="/assets/columna_4_pomocionales.png" alt="" width="800"  style="display: none;"></a>
  <a class="img_height" style="width: 510px; height: 100%; background-image: url(/assets/columna_5_diseño_corporativo.png); background-color: rgb(0, 0, 0); border-bottom-width: 0px; border-right-style: solid; border-right-width: 1px; border-right-color: rgb(0, 0, 0); overflow: hidden; background-repeat: no-repeat no-repeat;"><img class="alignnone size-medium wp-image-806" title="This street" src="/assets/columna_5_diseno_corporativo.png" alt="" style="display: none;"></a>
  <a class="img_height" style="width: 110px; height: 100%; background-image: url(/assets/columna_6_programacion_diseno.png); background-color: rgb(0, 0, 0); border-bottom-width: 0px; border-right-style: solid; border-right-width: 1px; border-right-color: rgb(0, 0, 0); overflow: hidden; background-repeat: no-repeat no-repeat;"><img class="alignnone size-medium wp-image-801" title="gift of light" src="/assets/columna_6_programacion_diseno.png" alt="" width="241" style="display: none;"></a>
  <a class="img_height" style="width: 110px; height: 100%; background-image: url(/assets/columna_7_produccion_audiovisual.png); background-color: rgb(0, 0, 0); border-bottom-width: 0px; border-right-style: solid; border-right-width: 1px; border-right-color: rgb(0, 0, 0); overflow: hidden; background-repeat: no-repeat no-repeat;"><img class="alignnone size-medium wp-image-803" title="Bamboo" src="/assets/columna_7_produccion_audiovisual.png" alt="" width="300"  style="display: none;"></a>
  <a class="img_height" style="width: 110px; height: 100%; background-image: url(/assets/columna_8_fotografia.png); background-color: rgb(0, 0, 0); border-bottom-width: 0px; border-right-width: 0px; overflow: hidden; background-repeat: no-repeat no-repeat;"><img class="alignnone size-medium wp-image-800" title="Aerial" src="/assets/columna_8_fotografia.png" alt="" width="800"  style="display: none;"></a>
</div>



<script type="text/javascript">
  $(document).ready(function() {
    $('#acc-menu2').AccordionImageMenu({
      'border' : 1,
      'duration': 400,
      'openDim': 625,
      'closeDim': 176,
      'fadeInTitle': false,
      'width':1700,
      'height':680
    });


});
</script>

app/views/static_pages/colectivo.js.erb
$('#content').html("<%= escape_javascript(render :partial => 'colectivo') %>" );
$('#content').css({'background-color':'#1f1f1f'}); 

app/views/static_pages/comunidad.js.erb
$('#content').html("<%= escape_javascript(render :partial => 'comunidad') %>" );
$('#content').css({'background-color':'#ececea'}); 

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/esencia.js.erb
$('#content').html("<%= escape_javascript(render :partial => 'esencia') %>" );

app/views/static_pages/home.html.erb
<div class="row-fluid">
	<header>
		<div class="span10 offset1"><%= link_to image_tag('logo_final.png', style: "max-width: 70%"), work_path, :remote => true, id: "main_menu" %></div>
		<nav style="display:block">
			<ul class="pointer">
				
				<li>
					<%= link_to "Comunidad", comunidad_path, :remote => true %>
				</li>
				<li>
					<%= link_to "Colectivo", colectivo_path, :remote => true %>
				</li>
				<li>
					<%= link_to "Esencia", esencia_path, :remote => true %>
				</li>
				<li>
					<%= link_to "Contacto", "#" %>
				</li>
			</ul>
		</nav>
	</header>
	<div class="row-fluid">
		<div style="margin-left:-78px">
			<div class="span9 offset3" id="content">
				<%= render 'work' %>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
$(function(){
	$('.pointer li').bind('click', function(){
		$('.pointer li > a').removeClass('active_link');
		$(this).find('a').addClass('active_link');
	});

	$('#main_menu').bind('click', function(){
		$('.pointer li > a').removeClass('active_link');
	});

});

</script>

app/views/static_pages/index.html.erb
    <!-- NAVBAR
    ================================================== -->
    <div class="navbar-wrapper">
      <!-- Wrap the .navbar in .container to center it within the absolutely positioned parent. -->
      <div class="container">

        <div class="navbar navbar-inverse">
          <div class="navbar-inner">
            <!-- Responsive Navbar Part 1: Button for triggering responsive navbar (not covered in tutorial). Include responsive CSS to utilize. -->
            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="brand" href="#">Columpiarte</a>
            <!-- Responsive Navbar Part 2: Place all navbar contents you want collapsed withing .navbar-collapse.collapse. -->
            <div class="nav-collapse collapse">
              <ul class="nav">
                <li class="active"><a href="#">Sobre</a></li>
                <li><a href="#item2">Servicios</a></li>
                <li><a href="#item3">Equipo</a></li>
                <li><a href="#item4">Contacto</a></li>
                <!-- Read about Bootstrap dropdowns at http://twitter.github.com/bootstrap/javascript.html#dropdowns -->
          
              </ul>
            </div><!--/.nav-collapse -->
          </div><!-- /.navbar-inner -->
        </div><!-- /.navbar -->

      </div> <!-- /.container -->
    </div><!-- /.navbar-wrapper -->



    <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide">
      <div class="carousel-inner">
        <div class="item active">
          <img src="http://www.publicdomainpictures.net/pictures/40000/velka/old-child-swing.jpg" alt="">
          <div class="container">
            <div class="carousel-caption">
              <h1>Somos Comunidad Creativa.</h1>
              <p class="lead">Colectivo profesional multidiciplinario. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <div style="margin: -25% -100% 0 0%; width:484px; height:291px; float:right; background-image: url('assets/collective.png')" class="span2 offset5">
              </div>
              <a class="btn btn-large btn-primary" href="#">Sign up today</a>
            </div>
          </div>
        </div>
        
        </div>
        <div class="">
          
        </div>
      </div>
    </div><!-- /.carousel -->

    <div id="item2" style="background-image: url('assets/escheresque.png'); padding-bottom:12%" class="row-fluid">
       <div style="margin-top:5%; margin-left:0" class="span12">
        <div style="padding:2%; margin-left:15%">
           <h1>Así cambiamos el mundo de los negocios.</h1>
          </div>
        <div class="row-fluid">
          <div class="span4">
            <div style="display:block">
              <a href="#" class="collection-services" style="background-image: url('http://www.it-outsource.info/images/conference.gif')">
                <div class="collection-text">
                  <h3>Planeación, desarrollo y gestión de proyectos.</h3>
                </div>
              </a>
            </div>
          </div>
          <div style="margin-left:2%" class="span4">
            <div style="display:block">
              <a href="#" class="collection-services" style="background-image: url('http://negocioaz.com/wp-content/uploads/2012/08/marketing_00-2.jpg')">
                <div class="collection-text">
                  <h3>Publicidad y medios.</h3>
                </div>
              </a>
            </div>
          </div>
          <div style="margin-left:2%" class="span4">
            <div style="display:block">
              <a href="#" class="collection-services" style="background-image: url('http://www.estudioabmedia.com/gpublicidad/images/stories/papeleria%20corporativa.png')">
                <div class="collection-text">
                  <h3>Imagen corporativa.</h3>
                </div>
              </a>
            </div>
          </div>
        </div>
      </div>
      <div style="margin-left:0" class="span12">
        <div class="row-fluid">
          <div class="span4">
            <div style="display:block">
              <a href="#" class="collection-services" style="background-image: url('http://liveyourlife1pib.files.wordpress.com/2013/03/reloj.jpg')">
                <div class="collection-text">
                  <h3>Actividades promocionales y BTL.</h3>
                </div>
              </a>
            </div>
          </div>
           <div style="margin-left:2%" class="span4">
            <div style="display:block">
              <a href="#" class="collection-services" style="background-image: url('http://www.avantbiz.com/design10/wp-content/uploads/2010/10/webdesign-capitalvc.jpg')">
                <div class="collection-text">
                  <h3>Diseño Web Corporativo.</h3>
                </div>
              </a>
            </div>
          </div>
          <div style="margin-left:2%" class="span4">
            <div style="display:block">
              <a href="#" class="collection-services" style="background-image: url('http://2.bp.blogspot.com/-LcsTNRGqavk/TZQjjf5iHkI/AAAAAAAABa8/ouhmqIa3Wtk/s1600/IMG_1792.JPG')">
                <div class="collection-text">
                  <h3>Producción audiovisual y fotografía.</h3>
                </div>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div id="item3" style="padding:5%; padding-bottom:10%; background-image: url('assets/retina_wood.png')" class="container-fluid">
     <div style="padding:1%; margin-left:15%">
        <h1>Nosotros</h1>
      </div>
      <!-- Three columns of text below the carousel -->
      <div class="row-fluid">
        <div class="span2">
          <img src="http://www.piccsy.com/investors/img/prefabs/daniel.svg"/>
          <h3 style="background-color:black; color:white; text-align:center">Joel</h3>
          <h3>Business</h3>
        </div>
        <div class="span2 offset1">
          <img src="http://www.piccsy.com/investors/img/prefabs/eric.svg"/>
          <h3 style="background-color:black; color:white; text-align:center">Ricky</h3>  <h3>Creative</h3>
        </div>
        <div class="span2 offset1">
          <img src="http://www.piccsy.com/investors/img/prefabs/matthew.svg"/>
          <h3 style="background-color:black; color:white; text-align:center">Julio</h3> 
          <h3>Reyveloeper</h3>
        </div>
        <div class="span2 offset1">
          <img src="http://www.piccsy.com/investors/img/prefabs/glenn.svg"/>
          <h3 style="background-color:black; color:white; text-align:center">Javier</h3> <h3>Video Expert</h3>
        </div>
      </div><!-- /.row -->
    </div>
    <!-- START THE FEATURETTES -->
    <!-- FOOTER -->
<div id="item4" style="padding-bottom:20%; margin-top:-1.7%; background-image: url('assets/white_bed_sheet.png')" class="well">
  <div class="container">
    <div style="margin-top:10%;" class="row">
      <div class="span12">
        <div class="span2">
          <h3>Mapa del Sitio</h3>
          <br/>
          <p style="font-size:1em; color:white"><a href="" style="color:#"> Home</a></p>
          <p style="font-size:1em; color:white"><a href="" style="color:#"> </a></p>
          <p style="font-size:1em; color:white"><a href="" style="color:#"> Lista de Precios</a></p>
          <p style="font-size:1em; color:white"><a href="" style="color:#"> Nosotros</a></p>
          <p style="font-size:1em; color:white"><a href="" style="color:#"> Blog</a></p>
          <p style="font-size:1em; color:white"><a href="" style="color:#"> Contacto</a></p>
        </div>

        <div class="span3">
          <h3> Nuestro Blog </h3>
          <h5>Lorem ipsum dolor </h5>
          <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus suscipit nisl ac metus porta placerat. Donec semper. consectetur<a href="" style="color:#">Leer más</a></p>
          <h5>Lorem ipsum dolor </h5>
          <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus suscipit nisl ac metus porta placerat. Donec semper. consectetur<a href="" style="color:#">Leer más</a></p>
        </div>

        <div class="span2">
          <h3> Contactanos</h3>
          <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. </p>
          <br/>
          <p> phone: 1-(555)-555-5555 <br/>
            email: help@pueblacapital.com <br/>
          </p>
        </div>

        <div class="span3 offset1">
            <h3>Newsletter</h3>
            <p> Subscribete y recibe las ultimas noticias </p>
            <form>
                  <div class="controls">
                    <input type="text" class="input-xlarge" placeholder="email" id="email">
                  </div>
                 <button type="submit" class="btn btn-success">Enviar</button>
               
            </form>
            <h3>Conéctate con nosotros</h3>
            <button type="submit" class="btn btn-info"><img src ="assets/twitter_blanco.png" />  Twitter</button>
            <button type="submit" class="btn btn-primary"><img src ="assets/facebook_blanco.png" />  facebook</button>
          </div>
        </div>
      </div> 
    </div> 
  </div> 
</div><!-- /.container -->
 <script>
            $('a').click(function(e){
                $('html,body').scrollTo(this.hash, this.hash);
                e.preventDefault();
            });

            // not really needed
            $(window).resize(function(){
                $('.page').css({
                    fontSize: Math.max(Math.min($(window).outerWidth() / (1 * 6), parseFloat(Number.POSITIVE_INFINITY)), parseFloat(Number.NEGATIVE_INFINITY)) + 'px',
                    lineHeight: $(window).height() + 'px'
                });
            }).resize();
        </script>

app/views/static_pages/work.js.erb
$('#content').html("<%= escape_javascript(render :partial => 'work') %>" );